### ISSUE TITLE
Cannot start service redis: Mounts denied

### ISSUE THREAD

**Issue by JMKelley** [wyveo/craftcms-docker#1]
Thanks for the craftcms docker image.

I'm getting the following error when trying to compose-up

```
ERROR: for redis  Cannot start service redis: Mounts denied: 
The path /data
is not shared from OS X and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.
```

Any idea why this is happening?

**Comment by infinitysgame** [comment]
[Docker for Mac shares](https://docs.docker.com/docker-for-mac/osxfs/#namespaces) only the `/Users/`, `/Volumes/`, `/private/`, and `/tmp` directories by default.

Try [adding the `/data`](https://docs.docker.com/docker-for-mac/#file-sharing) directory before running Docker.
