### ISSUE TITLE
Issues with default PHP memory?

### ISSUE THREAD

**Issue by vcao** [wyveo/craftcms-docker#11]
I've run into issues upgrading Craft on this build. It apparently has to do with use of Composer and PHP (php.ini) not having a larger enough memory limit.

See: https://github.com/craftcms/cms/issues/2159

Would increasing the base memory_limit to 256M or 512M fix this?

**Comment by colinwilson** [comment]
Sorry for the long delay.

> Would increasing the base memory_limit to 256M or 512M fix this?

Yes. Try increasing to 512M: https://github.com/wyveo/craftcms-docker/blob/ec699c2dad0510194ffaf24d7ef550d40289a312/Dockerfile#L7
