### ISSUE TITLE
nginx bind() to 0.0.0.0:80 failed (98: Address already in use)

### ISSUE THREAD

**Issue by c4milo** [wyveo/craftcms-docker#2]
I'm seeing a lot of these in my logs:

```
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
```

I think it can be fix by just leaving `listen [::]:80` in the nginx configuration. It will listen to both IPv4 and IPv6.

**Comment by infinitysgame** [comment]
Can you provide a little more info regarding your environment?

Unless you have some other process already using port 80, the `ipv6only=on` option should prevent this issue.
