### ISSUE TITLE
Cannot start service redis

### ISSUE THREAD

**Issue by ashbryant** [wyveo/craftcms-docker#25]
HI,

I'm new to craft CMS so please forgive me if this is a simple idiot asking a question.

I have just followed your docs on getting started with CCMS2 (the version my client is using) and I'm getting a couple of errors...

`ERROR: for the-abbey-docker_redis_1  Cannot start service redis: b'Mounts denied: \r\nThe path /data\r\nis not shared from OS X and is not known to Docker.\r\nYou can configure shared paths from Docker ->Creating the-abbey-docker_mariadb_1 ... done

ERROR: for redis  Cannot start service redis: b'Mounts denied: \r\nThe path /data\r\nis not shared from OS X and is not known to Docker.\r\nYou can configure shared paths from Docker -> Preferences... -> File Sharing.\r\nSee https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.\r\n.'
ERROR: Encountered errors while bringing up the project.`

I'm using os x mojave if that is an issue? Can you offer any help with this?

**Comment by colinwilson** [comment]
This might be related to issue #1

**Comment by blendjasper** [comment]
I was able to get that part solved on my mac. I created /data folder by creating a symbolic link to a local folder:
lrwxr-xr-x   1 root  wheel    18 Sep 29 15:50 data -> /Users/jasper/data

Then I added the folder to Docker sharing preferences as you can see in the screenshot:
https://www.evernote.com/l/AV7ocqLMIfNJIZ13MNSsFnY0N_snZhghRWY

You should be able to get it started from there. The next problem is getting access to Craft. You should have a look at https://github.com/wyveo/craftcms-docker/issues/19.
