### ISSUE TITLE
Volumes folder not being created

### ISSUE THREAD

**Issue by devlemire** [wyveo/craftcms-docker#27]
![screen shot 2018-11-13 at 2 35 12 pm](https://user-images.githubusercontent.com/19179440/48444538-7bc9f380-e751-11e8-8a6d-b6a567e5452b.png)

I've followed the instructions step by step until it comes to editing the Craft 3 files. For some reason my Docker is not actually creating the directory for the volume. Any ideas here?

**Comment by colinwilson** [comment]
Are you using Docker for Mac?
