### ISSUE TITLE
Use with Zeit Now?

### ISSUE THREAD

**Issue by fredrik-sogaard** [wyveo/craftcms-docker#3]
Just curious, have you had any luck using this with [Zeit Now](https://zeit.co/now)? Here's their short Docker docs: https://zeit.co/docs/deployment-types/docker

I'm only getting 500 internal errors when testing the Craft 3 Beta container. Although when I try to go to /admin I'm correctly redirected to /admin/install, so something is working.

**Comment by colinwilson** [comment]
[Doesn't look like Zeit Now supports Docker Compose currently](https://github.com/zeit/now-cli/issues/294). So the accompanying containers (PostgreSQL;Memcached) aren't being linked and started.
