### ISSUE TITLE
When I stop the container, I need to set the craft from scratch in craft v3

### ISSUE THREAD

**Issue by berkcandmir** [wyveo/craftcms-docker#30]
Hi,

I'm already using your craft 2 docker image and very happy about it. Few days ago, i wanted to create a new site with craft 3 and use your image but i'm facing with a big problem. When i stop the container and up again, i have to install craft from scratch and all I do is disappear. Any idea?

**Comment by colinwilson** [comment]
Need a little more info on your environment.

Sounds like your Postgres (or Web) container data is not persisting.

Is this 'wipe' happening when you stop/start just the `web` container?

What's the result of `$ docker volume ls` after initial install? Can you confirm your craft and postgres volumes have been successfully created?

**Comment by colinwilson** [comment]
Closing. If this is still an issue please reply.
