### ISSUE TITLE
Plans to update this Docker image

### ISSUE THREAD

**Issue by pacifier17** [wyveo/craftcms-docker#34]
Hi,
I wanted to check if you have any plans to rebuild and re-upload this image to Docker Hub? The reason being that the version of Debian that it is based on is old and has a lot of vulnerabilities. I see that Debian has patched their buster version, so was wondering if you will be re-pulling that base image and re-building your image?

**Comment by colinwilson** [comment]
@pacifier17 Yep. Thanks for the info. Just have to make time. I should get around to it in the next few days.

**Comment by pacifier17** [comment]
Perfect. Thanks @colinwilson! Will keep an eye out for the new release.

**Comment by colinwilson** [comment]
No Problem. It's long overdue to be honest.

**Comment by pacifier17** [comment]
Hey @colinwilson, hope you are well! Just wanted to check how you are getting along with updating the image? Happy to help out in any way.

**Comment by colinwilson** [comment]
Image updated (eeabe8e286628340847f5b40d4609ea44ce366ca).

Do let me know if you encounter any issues?
