### ISSUE TITLE
wyveo/craftcms-docker:php74

### ISSUE THREAD

**Issue by nickwanhere** [wyveo/craftcms-docker#39]
Hi there,

Used couple times before. Pretty easy to get it running!

I saw there is an upgrade to latest version 3.4.28.1, tried it and it said 
```ERROR: manifest for wyveo/craftcms-docker:php74 not found```

Used wyveo/craftcms-docker:3.4.28.1 instead in dokcer-composer.yml , seems to work for me.

**Comment by colinwilson** [comment]
Thanks. 

Fixed by 996ad2a52bf6740e6f14037575b59c141468c825
