### ISSUE TITLE
Craft v3 plugins

### ISSUE THREAD

**Issue by btpoe** [wyveo/craftcms-docker#4]
Craft v3 recommends using composer to add plugins to a project. Currently, I've been running `docker exec` to run the composer command, but that means I need to rerun the command any time I need to restart the web container. Do you have a recommended way of adding plugins?

**Comment by askogrand** [comment]
@btpoe You can use this dockerfile as a base, and extend it to add your own plugins every time you spin up docker. Your `dockerfile` may look like this:

```
FROM wyveo/craftcms-docker:craft3beta

WORKDIR /usr/share/nginx/

RUN composer require someuser/someproject
```
