### ISSUE TITLE
Craft Update to 3.5.16

### ISSUE THREAD

**Issue by skoch** [wyveo/craftcms-docker#41]
Hi all.

We've been running into issues with a Gatsby plugin and the Craft team has recommended updating to use a [newer plugin to connect Craft and Gatsby](https://github.com/craftcms/gatsby-source-craft) that they've developed.

This plugin requires Craft **3.5.16** or newer.

Are there any plans to update?

Thank you.

**Comment by colinwilson** [comment]
> Are there any plans to update?

Updated to 3.6.0.1 by 9fe75a1.

**Comment by skoch** [comment]
Thank you so much for the speed on this, much appreciated @colinwilson! 

🙏

**Comment by colinwilson** [comment]
@skoch You're welcome 👍
