### ISSUE TITLE
Incorrect DB credentials blocks installation

### ISSUE THREAD

**Issue by askogrand** [wyveo/craftcms-docker#9]
Currently, navigating to http://0.0.0.0/admin/install displays the following message:

```Can't connect to the database with the credentials supplied in db.php. Please double check them and try again.```

When I echo out which ENV variables `db.php` sees, I get the following:

```
(
    [driver] => pgsql
    [server] => 
    [user] => craft3beta
    [password] => 
    [database] => 
    [schema] => 
    [tablePrefix] => 
    [port] => 5432
)
```

**Comment by hylinkdigital** [comment]
I have the same error message for the craft3 branch.

Are there root credentials we can use temporarily?

**Comment by askogrand** [comment]
@hylinkdigital You can clone/fork the project and change the `.env.sample` to lose the `CRAFT_` before every environment var.

**Comment by hylinkdigital** [comment]
@askogrand - thanks. Yes, I manually altered the environment variable references via bash, but that won't persist.

How do I get my local .env changes to apply to the container? Do I have to move the .env file into a volume?

**Comment by askogrand** [comment]
Create your own Dockerfile, and reference this one. Also have your own `.env.sample`.

Your Dockerfile will look like:

```
FROM wyveo/craftcms-docker:craft3beta

ADD .env.sample /usr/share/nginx/.env

```

**Comment by colinwilson** [comment]
@askogrand sorry for the long delay.

Fixed the environment variables in the [docker-compose.yml](86c4c02744f899e813356731a23b957237841f4e) to resolve this issue.
